### ISSUE TITLE
Uncaught TypeError: this.element.uniqueId is not a function when upgrading to 4.0.1

### ISSUE THREAD

**Issue by gitchuckles** [struts-community-plugins/struts2-jquery#94]
I'm trying to upgrade from 3.7.1 to the 4.0.1 release and I get the following error when loading a jsp
we don't have any uniqueId calls in our code. any suggestions?
VM122:68 Uncaught TypeError: this.element.uniqueId is not a function
    at $.(anonymous function).(anonymous function)._create (eval at globalEval (http://localhost:8080/dev/struts/js/base/jquery-2.2.4.js:343:5), <anonymous>:68:5)
    at $.(anonymous function).(anonymous function).eval [as _create] (eval at globalEval (http://localhost:8080/dev/struts/js/base/jquery-2.2.4.js:343:5), <anonymous>:132:25)
    at $.(anonymous function).(anonymous function)._createWidget (eval at globalEval (http://localhost:8080/dev/struts/js/base/jquery-2.2.4.js:343:5), <anonymous>:329:8)
    at new $.(anonymous function).(anonymous function) (eval at globalEval (http://localhost:8080/dev/struts/js/base/jquery-2.2.4.js:343:5), <anonymous>:87:9)
    at HTMLUListElement.eval (eval at globalEval (http://localhost:8080/dev/struts/js/base/jquery-2.2.4.js:343:5), <anonymous>:269:30)
    at Function.each (http://localhost:8080/dev/struts/js/base/jquery-2.2.4.js:365:19)
    at jQuery.fn.init.each (http://localhost:8080/dev/struts/js/base/jquery-2.2.4.js:137:17)
    at jQuery.fn.init.$.fn.(anonymous function) [as menu] (eval at globalEval (http://localhost:8080/dev/struts/js/base/jquery-2.2.4.js:343:5), <anonymous>:261:9)
    at $.(anonymous function).(anonymous function)._create (eval at globalEval (http://localhost:8080/dev/struts/js/base/jquery-2.2.4.js:343:5), <anonymous>:217:5)
    at $.(anonymous function).(anonymous function).eval [as _create] (eval at globalEval (http://localhost:8080/dev/struts/js/base/jquery-2.2.4.js:343:5), <anonymous>:132:25)
~

**Comment by sdutry** [comment]
@gitchuckles 
we are aware of this issue.

It should be fixed with the fix in #89 .

Unfortunately it means you'll have to wait till version 4.0.2 is released for a definitive fix.

#### Known workaround: 
use `loadAtOnce="true"` attribute on your current `sj:head` tag

Please let us know if this workaround works for you.

**Comment by flofourcade** [comment]
We re working on this isdue. See #89. Using loadAtOnce="true" should fix this problem in your <sj:head /> tag should make your jsp working. Alternatively you can try the 4.0.2 snapshot version where fixes have been applied.

**Comment by gitchuckles** [comment]
thanks, the workaround worked

**Comment by jogep** [comment]
New release 4.0.2 with fix is now released.
